spring.cloud.gateway.rsocket.client:
  route-id: 3
  service-name: pong
  tags:
    INSTANCE_NAME: pong3
  broker:
    host: localhost
    port: 7002

server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO
---
spring:
  profiles: server
pong:
  client: false

---
spring:
  profiles: pong4
spring.cloud.gateway.rsocket.client:
  route-id: 4
  service-name: pong
  tags:
    INSTANCE_NAME: pong4

---
spring:
  profiles: gateway2
  cloud.gateway.rsocket.client:
    broker:
      host: localhost
      port: 7003
