spring.cloud.gateway.rsocket.enabled: false
server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO
---
spring:
  profiles: server
pong:
  client: false

---
spring:
  profiles: pongproxy
  cloud.gateway.rsocket.server.port: 7003