spring:
  cloud:
    gateway:
      rsocket:
        id: gateway1

server:
  port: 0

logging:
  level:
    org.springframework.cloud.gateway.rsocket: DEBUG
---
spring:
  profiles: pongproxy
  cloud:
    gateway:
      rsocket:
        id: gateway2
        server:
          port: 7003