spring:
  cloud:
    gateway:
      rsocket:
        id: gateway1
        route-id: 11
        service-name: gateway

logging:
  level:
    org.springframework.cloud.gateway.rsocket: DEBUG
#    org.springframework.cloud.gateway.rsocket: TRACE
---
spring:
  profiles: gateway2
  rsocket:
    server:
      port: 7003
  cloud:
    gateway:
      rsocket:
        id: gateway2
        route-id: 12
        service-name: gateway
        brokers:
          - host: localhost
            port: 7002
