spring:
  cloud:
    gateway:
      rsocket:
        id: gateway1

server:
  port: 0

logging:
  level:
    org.springframework.cloud.gateway.rsocket: DEBUG
#    org.springframework.cloud.gateway.rsocket: TRACE
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: pongproxy
  rsocket:
    server:
      port: 7003
  cloud:
    gateway:
      rsocket:
        id: gateway2
management:
  server:
    port: 18081
  endpoints:
    web:
      exposure:
        include: '*'