io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000001
  service-name: ping
  tags:
    INSTANCE_NAME: ping1
  address:
    pong-rc:
      service_name: pong
  brokers:
    - tcp:
        host: localhost
        port: 8002

server:
  port: 0
#debug: true
---
spring.config.activate.on-profile: ping2

io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000002
  tags:
    INSTANCE_NAME: ping2

ping:
  request-type: request_response

---
spring.config.activate.on-profile: broker2

io.rsocket.routing.client:
    brokers:
      - tcp:
          host: localhost
          port: 8003

